
/* Actualizar las rutas de los datafiles*/
CREATE TABLESPACE JOYERIA DATAFILE '\APP\LECAM\PRODUCT\18.0.0\ORADATA\XE\JOYERIA.dbf' size 20M AUTOEXTEND ON MAXSIZE UNLIMITED;
CREATE TEMPORARY TABLESPACE TJOYERIA TEMPFILE '\APP\LECAM\PRODUCT\18.0.0\ORADATA\XE\TJOYERIA.DBF' size 512M REUSE EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M; 

alter session set "_ORACLE_SCRIPT"=true;
CREATE USER JOYERIA IDENTIFIED BY JOYERIA123 DEFAULT TABLESPACE JOYERIA TEMPORARY TABLESPACE TJOYERIA;
GRANT CONNECT,RESOURCE TO JOYERIA;

/*JOYERIA*/

CREATE SEQUENCE  JOYERIA.S_PROD_ID  MINVALUE 1 MAXVALUE 999999999999 
INCREMENT BY 1 
START WITH 1;

CREATE  TABLE JOYERIA.MATERIAL(
MATE_ID NUMBER(10,0) NOT NULL,
MATE_NOMBRE VARCHAR2(100) NOT NULL,
CONSTRAINT MATE_ID_PK PRIMARY KEY(MATE_ID)
);

CREATE  TABLE JOYERIA.TIPO(
TIPO_ID NUMBER(10,0) NOT NULL,
TIPO_NOMBRE VARCHAR2(100) NOT NULL,
CONSTRAINT TIPO_ID_PK PRIMARY KEY(TIPO_ID)
);


CREATE  TABLE JOYERIA.PRODUCTO(
PROD_ID NUMBER(10,0) NOT NULL,
PROD_NOMBRE VARCHAR2(100) NOT NULL,
MATE_ID NUMBER(10,0) NOT NULL,
TIPO_ID NUMBER(10,0) NOT NULL,
PROD_PRECIO NUMBER(10,0) NOT NULL,
PROD_PESO NUMBER(6,2) NOT NULL,
PROD_FECHACAMBIO DATE NOT NULL,
CONSTRAINT PROD_ID_PK PRIMARY KEY(PROD_ID),
CONSTRAINT PROD_MATE_FK FOREIGN KEY(MATE_ID) REFERENCES JOYERIA.MATERIAL(MATE_ID),
CONSTRAINT PROD_TIPO_FK FOREIGN KEY(TIPO_ID) REFERENCES JOYERIA.TIPO(TIPO_ID)
);

Insert into JOYERIA.TIPO (TIPO_ID,TIPO_NOMBRE) values ('1','Anillo');
Insert into JOYERIA.TIPO (TIPO_ID,TIPO_NOMBRE) values ('2','Cadena');
Insert into JOYERIA.TIPO (TIPO_ID,TIPO_NOMBRE) values ('3','Reloj');

Insert into JOYERIA.MATERIAL (MATE_ID,MATE_NOMBRE) values ('1','Oro');
Insert into JOYERIA.MATERIAL (MATE_ID,MATE_NOMBRE) values ('2','Plata');

commit;

